[project]
name = "dpc-client-core"
version = "0.1.0"
description = ""
authors = [
    {name = "Mike Shevchenko",email = "mikhashev@yandex.ru"}
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ollama (>=0.6.0,<0.7.0)",
    "websockets (>=15.0.1,<16.0.0)",
    "dpc-protocol @ file:///C:/Users/mike/Documents/dpc-messenger/dpc-protocol",
    "toml (>=0.10.2,<0.11.0)",
    "openai (>=2.6.1,<3.0.0)",
    "anthropic (>=0.72.0,<0.73.0)",
    "httpx (>=0.28.1,<0.29.0)",
    "aiortc (>=1.14.0,<2.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.dependencies]
dpc-protocol = {develop = true}
